### ISSUE TITLE
Out-of-date version of syn and quote

### ISSUE THREAD

**Issue by kornelski** [sile/trackable_derive#1]
This crate is using old versions of `syn` and `quote`. Could you update them to the latest and make a new release?

**Comment by sile** [comment]
Thank you for letting me know that. I'll update the dependencies soon.

**Comment by sile** [comment]
Published [v0.1.3](https://crates.io/crates/trackable_derive/0.1.3) that depends on the up-to-date `syn` and `quote` crates.
